[tool.poetry]
name = "htbam-notebooks"
version = "0.1.0"
description = ""
authors = ["duncan-muir <muir.duncan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
